config/routes.rb
Trakker::Application.routes.draw do

  resources :scouts do 
    resources :advancements
    match 'advancements/:id/updateDate' => 'advancements#updateDate'
  end

end

app/models/advancement.rb
class Advancement < ActiveRecord::Base
  attr_accessible :rank, :scout_id
  belongs_to :scout
  has_one :boy_scout_rank, :dependent => :destroy
  has_one :tenderfoot_rank, :dependent => :destroy
  has_one :second_class_rank, :dependent => :destroy
  has_one :first_class_rank, :dependent => :destroy
  has_one :star_rank, :dependent => :destroy
  has_one :life_rank, :dependent => :destroy
  has_one :eagle_rank, :dependent => :destroy
  accepts_nested_attributes_for :boy_scout_rank
  accepts_nested_attributes_for :tenderfoot_rank
  accepts_nested_attributes_for :second_class_rank
  accepts_nested_attributes_for :first_class_rank
  accepts_nested_attributes_for :star_rank
  accepts_nested_attributes_for :life_rank
  accepts_nested_attributes_for :eagle_rank
  attr_accessible :boy_scout_rank_attributes
  attr_accessible :tenderfoot_rank_attributes
  attr_accessible :second_class_rank_attributes
  attr_accessible :first_class_rank_attributes
  attr_accessible :star_rank_attributes
  attr_accessible :life_rank_attributes
  attr_accessible :eagle_rank_attributes

  def toggle_approve(scout, con, req)

    puts "TOGGLE_APPROVE"
    puts "??????????????????????????????????"
    puts scout.id
    puts con
    puts req
    advancement = scout.advancement
    rank = scout.advancement.send(con)
    puts rank.class

   	if(scout.advancement.send(con).send(req).blank?)
   		scout.advancement.send(con).send(req + '=', "jh")
   		puts "Inserted Name"
   		puts scout.advancement.send(con).send(req)
      puts scout.advancement.send(con).send(req + "_date" + '=', Date.today.to_s)
      puts "Inserted Date"
   	else
   		scout.advancement.send(con).send(req + '=', "")
   		puts "Inserted Blank"
   		puts scout.advancement.send(con).send(req)
      puts scout.advancement.send(con).send(req + "_date" + '=', "")
      puts "Removed Date"
   	end
   	puts "SAVED"
   	scout.advancement.send(con).save
   	puts "FINISHED"
  end

  def update_date(scout, con, req, date)
    advancement = scout.advancement
    rank = scout.advancement.send(con)
    req_complete = req + "_date"
    scout.advancement.send(con).send(req_complete + '=', date)
    scout.advancement.send(con).send(req + '=', "jh")
    scout.advancement.send(con).save
    puts "Date Saved"
  end

end

app/controllers/advancements_controller.rb
class AdvancementsController < ApplicationController
  before_filter :load_scout
  # GET /advancements
  # GET /advancements.json
  def index
    @boy_scout_partial = "boy_scout.html.erb"
    puts "INDEX"
    puts params.inspect
    @advancement = Advancement.find(params[:scout_id])
    @boy_scout = @advancement.boy_scout_rank
    @tenderfoot = @advancement.tenderfoot_rank
    @second_class = @advancement.second_class_rank
    @first_class = @advancement.first_class_rank
    @star = @advancement.star_rank
    @life = @advancement.life_rank
    @eagle = @advancement.eagle_rank
    @eagleBadges = EagleRequiredMeritBadges.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @advancements }
    end
  end

  # GET /advancements/1
  # GET /advancements/1.json
  def show
    puts "SHOW"
    puts params.inspect
    puts "]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]"


    scout = Scout.find(params[:scout_id])
    @advance = scout.advancement
    con = params[:con]
    req = params[:req]
    puts con
    puts req
    @link = @advance.toggle_approve(scout, con, req)
    respond_to do |format|
      format.json
    end
  end

  # GET /advancements/new
  # GET /advancements/new.json
  def new
    @advancement = Advancement.new(params[:advancement])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @advancement }
    end
  end

  # GET /advancements/1/edit
  def edit
    @advancement = Advancement.find(params[:id])
  end

  # POST /advancements
  # POST /advancements.json
  def create
    @advancement = Advancement.new(params[:advancement])

    respond_to do |format|
      if @advancement.save
        format.html { redirect_to @advancement, notice: 'Advancement was successfully created.' }
        format.json { render json: @advancement, status: :created, location: @advancement }
      else
        format.html { render action: "new" }
        format.json { render json: @advancement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /advancements/1
  # PUT /advancements/1.json
  def update
    @advancement = Advancement.find(params[:id])

    respond_to do |format|
      if @advancement.update_attributes(params[:advancement])
        format.html { redirect_to @advancement, notice: 'Advancement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @advancement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advancements/1
  # DELETE /advancements/1.json
  def destroy
    @advancement = Advancement.find(params[:id])
    @advancement.destroy

    respond_to do |format|
      format.html { redirect_to advancements_url }
      format.json { head :no_content }
    end
  end

  def updateDate
    puts "UPDATE DATE"
    scout = Scout.find(params[:scout_id])
    @advance = scout.advancement
    con = params[:con]
    req = params[:req]
    date = params[:date]
    puts con
    puts req
    @link = @advance.update_date(scout, con, req, date)
    respond_to do |format|
      format.json
    end
  end

  private
    def load_scout
      @scout = Scout.find(params[:scout_id])
    end
end

app/helpers/advancements_helper.rb
module AdvancementsHelper
end

app/views/advancements/_boy_scout.html.erb
<%= form_for :boy_scout do |f| %>
<table class="table table-hover" data-controller="boy_scout_rank">
	<thead>
		<tr>
			<th colspan="4" align="left"><h2> Boy Scout Rank</h2></th>
		</tr>
		<tr>
			<th>Number</th>
			<th>Requirements</th>
			<th>Completed</th>
			<th>Date</th>
		</tr>
	</thead>
	<tbody>
		<tr data-name="one_li">
			<td>1</td>
			<td>Meet the age requirements. Be a boy who is 11 years old, or one who has completed the fifth grade or earned the Arrow of Light Award and is at least 10 years old, but is not yet 18 years old.</td>
			<td>
				<% if(!@boy_scout.one_li.blank?) %>
				<%=  image_tag("checkmark.png") %>
				<% end %>
			</td>
			<td>
				<%= f.text_field :one_li_date, :class => "datepicker" %>
			</td>
		</tr>
		<tr data-name="two_li">
			<td>2</td>
			<td>Find a Scout troop near your home.</td>
			<td> <% if(!@boy_scout.two_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
				<%= f.text_field :two_li_date, :class => "datepicker" %>
			</td>
		</tr>
		<tr data-name="three_li">
			<td>3</td>
			<td>Complete a Boy Scout application and health history signed by your parent or guardian.</td>
			<td> <% if(!@boy_scout.three_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
				<%= f.text_field :three_li_date, :class => "datepicker" %>
			</td>
		</tr>
				<tr data-name="four_li">
			<td>4</td>
			<td>Repeat the Pledge of Allegiance.</td>
			<td> <% if(!@boy_scout.four_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
				<%= f.text_field :four_li_date, :class => "datepicker" %>
			</td>
		</tr>
				<tr data-name="five_li">
			<td>5</td>
			<td>Demonstrate the Scout sign, salute, and handshake.</td>

			<%= puts @boy_scout.five_li %>
			<td> <% if(!@boy_scout.five_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
				<%= f.text_field :five_li_date, :class => "datepicker" %>
			</td>
		</tr>
				<tr data-name="six_li">
			<td>6</td>
			<td>Demonstrate tying the square knot (a joining knot).</td>
			<td> <% if(!@boy_scout.six_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
				<%= f.text_field :six_li_date, :class => "datepicker" %>
			</td>
		</tr>
				<tr data-name="seven_li">
			<td>7</td>
			<td>Understand and agree to live by the Scout Oath or Promise, Law, motto, and slogan, and the Outdoor Code.</td>
			<td> <% if(!@boy_scout.seven_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
				<%= f.text_field :seven_li_date, :class => "datepicker" %>
			</td>
		</tr>
				<tr data-name="eight_li">
			<td>8</td>
			<td>Describe the Scout badge.</td>
			<td> <% if(!@boy_scout.eight_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
				<%= f.text_field :eight_li_date, :class => "datepicker" %>
			</td>
		</tr>
				<tr data-name="nine_li">
			<td>9</td>
			<td>Complete the pamphlet exercises. With your parent or guardian, complete the exercises in the pamphlet How to Protect Your Children From Child Abuse: A Parent’s Guide.</td>
			<td> <% if(!@boy_scout.nine_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
				<%= f.text_field :nine_li_date, :class => "datepicker" %>
			</td>
		</tr>
				<tr data-name="ten_li">
			<td>10</td>
			<td>Participate in a Scoutmaster conference. Turn in your Boy Scout application and health history form signed by your parent or guardian, then participate in a Scoutmaster conference</td>
			<td> <% if(!@boy_scout.ten_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
				<%= f.text_field :ten_li_date, :class => "datepicker" %>
			</td>
		</tr>

	</tbody>
</table>
<%= javascript_tag do %>
  window.advancementId = "<%=j @boy_scout.id.to_s %>";
<% end %>
<% end %>

app/views/advancements/_eagle.html.erb
<%= form_for :eagle do |f|  %>
<table class="table table-hover" data-controller="eagle_rank">
  <thead>
    <tr>
      <th colspan="4" align="left"><h2>Eagle Rank</h2></th>
    </tr>
    <tr>
      <th>Number</th>
      <th>Requirements</th>
      <th>Completed</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <tr data-name="one_li">
      <td>1</td>
      <td>Be active in your troop, team, crew, or ship for a period of at least six months after you have achieved the rank of Life Scout.</td>
      <td> <% if(!@eagle.one_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:one_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="two_li">
      <td>2</td>
      <td>Demonstrate that you live by the principles of the Scout Oath and Law in your daily life. List the names of individuals who know you personally and would be willing to provide a recommendation on your behalf, including parents/guardians, religious, educational, and employer references.</td>
      <td> <% if(!@eagle.two_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:two_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="three_li">
      <td>3</td>
      <td>
      <p>
        Earn a total of 21 merit badges (10 more than you already have), including the following:
      </p>
      <p>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
      </p></td>
      <td> <% if(!@eagle.three_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:three_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="four_li">
      <td>4</td>
      <td>While a Life Scout, serve actively for a period of six months in one or more of the following positions of responsibility:
        <p>a. Boy Scout troop. Patrol leader, assistant senior patrol leader, senior patrol leader, Venture patrol leader, troop guide, Order of the Arrow troop representative, den chief, scribe, librarian, historian, quartermaster, junior assistant Scoutmaster, chaplain aide, instructor, Webmaster, or Leave No Trace Trainer.</p>
        <p>b. Varsity Scout team. Captain, cocaptain, program manager, squad leader, team secretary, Order of the Arrow team representative, librarian, historian, quartermaster, chaplain aide, instructor, den chief, Webmaster, or Leave No Trace Trainer.</p>
        <p>c. Venturing crew/ship. President, vice president, secretary, treasurer, quartermaster, historian, den chief, guide, boatswain, boatswain's mate, yeoman, purser, storekeeper, Webmaster, or Leave No Trace Trainer.</p>
      </td>
      <td> <% if(!@eagle.four_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:four_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="five_li">
      <td>5</td>
      <td>While a Life Scout, plan, develop, and give leadership to others in a service project helpful to any religious institution, any school, or your community. (The project must benefit an organization other than Boy Scouting.) A project proposal must be approved by the organization benefiting from the effort, your unit leader and unit committee, and the council or district before you start. You must use the Eagle Scout Service Project Workbook, BSA publication No. 512-927, in meeting this requirement. (To learn more about the Eagle Scout service project, see the Guide to Advancement, topics 9.0.2.0 through 9.0.2.15.)<td> <% if(!@eagle.five_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:five_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="six_li">
      <td>6</td>
      <td>Take part in a unit leader conference.</td>
      <td> <% if(!@eagle.six_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:six_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="seven_li">
      <td>7</td>
      <td>Successfully complete an Eagle Scout board of review.</td>
      <td> <% if(!@eagle.seven_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:seven_li_date, :class => 'datepicker')%> </td>
    </tr>
  </tbody>
</table>
<%= javascript_tag do %>
window.advancementId = "<%=j @eagle.id.to_s %>";
<% end %>
<% end %>

app/views/advancements/_form.html.erb
<%= form_for(@advancement) do |f| %>
  <% if @advancement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advancement.errors.count, "error") %> prohibited this advancement from being saved:</h2>

      <ul>
      <% @advancement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scout_id %><br />
    <%= f.number_field :scout_id %>
  </div>
  <div class="field">
    <%= f.label :rank %><br />
    <%= f.text_field :rank %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advancements/_life.html.erb
<%= form_for :life do |f|  %>
<table class="table table-hover" data-controller="life_rank">
  <thead>
    <tr>
      <th colspan="4" align="left"><h2>Life Rank</h2></th>
    </tr>
    <tr>
      <th>Number</th>
      <th>Requirements</th>
      <th>Completed</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <tr data-name="one_li">
      <td>1</td>
      <td>Be active in your unit (and patrol if you are in one) for at least six months as a Star Scout.</td>
      <td> <% if(!@life.one_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:one_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="two_li">
      <td>2</td>
      <td>Demonstrate Scout spirit by living the Scout Oath (Promise) and Scout Law in your everyday life.</td>
      <td> <% if(!@life.two_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:two_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="three_li">
      <td>3</td>
      <td>
      <p>
        Earn five more merit badges (so that you have 11 in all), including any three more from the required list for Eagle. (See the Eagle Rank Requirements, number 3, for this list.) A Scout may choose any of the 15 required merit badges in the 12 categories to fulfill this requirement.
      </p>
      <p>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
        <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
      </p></td>
      <td> <% if(!@life.three_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:three_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="four_li">
      <td>4</td>
      <td>While a Star Scout, take part in service project(s) totaling at least six hours of work. These projects must be approved by your Scoutmaster.</td>
      <td> <% if(!@life.four_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:four_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="five_li">
      <td>5</td>
      <td>While a Star Scout, serve actively for six months in one or more of the troop positions of responsibility listed in requirement 5 for Star Scout (or carry out a Scoutmaster-assigned leadership project to help the troop). <td> <% if(!@life.five_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:five_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="six_li">
      <td>6</td>
      <td>While a Star Scout, use the EDGE method to teach a younger Scout the skills from ONE of the following six choices, so that he is prepared to pass those requirements to his unit leader’s satisfaction:
        <p>a.  Second Class—7a and 7c (first aid)</p>
        <p>b.  Second Class—1a (outdoor skills)</p>
        <p>c.  Second Class—3c, 3d, 3e, and 3f (cooking/camping)</p>
        <p>d.  First Class—8a, 8b, 8c, and 8d (first aid)</p>
        <p>e.  First Class—1, 7a, and 7b (outdoor skills)</p>
        <p>f.  First Class—4a, 4b, and 4d (cooking/camping)</p>
        <p>g.  Three requirements from one of the required Eagle merit badges, as approved by your unit leader.</p>
      </td>
      <td> <% if(!@life.six_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:six_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="seven_li">
      <td>7</td>
      <td>Take part in a Scoutmaster conference.</td>
      <td> <% if(!@life.seven_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:seven_li_date, :class => 'datepicker')%> </td>
    </tr>
    <tr data-name="six_li">
      <td>6</td>
      <td>Complete your board of review.</td>
      <td> <% if(!@life.six_li.blank?) %>
      <%=  image_tag("checkmark.png") %>
      <% end %> </td>
      <td> <%= f.text_field(:six_li_date, :class => 'datepicker')%> </td>
    </tr>
  </tbody>
</table>
<%= javascript_tag do %>
window.advancementId = "<%=j @life.id.to_s %>";
<% end %>
<% end %>

app/views/advancements/_star.html.erb
<%= form_for :star do |f|  %>
<table class="table table-hover" data-controller="star_rank">
	<thead>
		<tr>
			<th colspan="4" align="left"><h2>Star Rank</h2></th>
		</tr>
		<tr>
			<th>Number</th>
			<th>Requirements</th>
			<th>Completed</th>
			<th>Date</th>
		</tr>
	</thead>
	<tbody>
		<tr data-name="one_li">
			<td>1</td>
			<td>Be active in your unit (and patrol if you are in one) for at least four months as a First Class Scout.</td>
			<td>
				 <% if(!@star.one_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
				<%= f.text_field(:one_li_date, :class => 'datepicker')%>
			</td>
		</tr>
		<tr data-name="two_li">
			<td>2</td>
			<td>Demonstrate Scout spirit by living the Scout Oath (Promise) and Scout Law in your everyday life.</td>
			<td> <% if(!@star.two_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
        <%= f.text_field(:two_li_date, :class => 'datepicker')%>
      </td>
		</tr>
		<tr data-name="three_li">
			<td>3</td>
			<td>
				<p>Earn six merit badges, including any four from the required list for Eagle.</p>
				<p>
          <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
          <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
          <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
          <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
          <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
          <%= select_tag "", options_from_collection_for_select(@eagleBadges, 'id', 'name'), :prompt => "--"  %>
				</p>
			</td>
			<td> <% if(!@star.three_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
        <%= f.text_field(:three_li_date, :class => 'datepicker')%>
      </td>
		</tr>
				<tr data-name="four_li">
			<td>4</td>
			<td>While a First Class Scout, take part in service project(s) totaling at least six hours of work. These projects must be approved by your Scoutmaster.</td>
			<td> <% if(!@star.four_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
        <%= f.text_field(:four_li_date, :class => 'datepicker')%>
      </td>
		</tr>
				<tr data-name="five_li">
			<td>5</td>
			<td><p>While a First Class Scout, serve actively for four months in one or more of the following positions of responsibility (or carry out a Scoutmaster-assigned leadership project to help the unit): </p>

<p>Boy Scout troop. Patrol leader, assistant senior patrol leader, senior patrol leader, Venture patrol leader, troop guide, Order of the Arrow troop representative, den chief, scribe, librarian, historian, quartermaster, bugler, junior assistant Scoutmaster, chaplain aide, instructor, troop Webmaster, or Leave No Trace trainer.</p>

<p>Varsity Scout team. Captain, cocaptain, program manager, squad leader, team secretary, Order of the Arrow troop representative, librarian, historian, quartermaster, chaplain aide, instructor, den chief, team Webmaster, or Leave No Trace trainer.</p>

<p>Venturing crew/ship. President, vice president, secretary, treasurer, den chief, quartermaster, historian, guide, boatswain, boatswain’s mate, yeoman, purser, storekeeper, crew/ship Webmaster, or Leave No Trace trainer.</p></td>
			<td> <% if(!@star.five_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
        <%= f.text_field(:five_li_date, :class => 'datepicker')%>
      </td>
		</tr>
				<tr data-name="six_li">
			<td>6</td>
			<td>Take part in a Scoutmaster conference.</td>
			<td> <% if(!@star.six_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
        <%= f.text_field(:six_li_date, :class => 'datepicker')%>
      </td>
		</tr>
				<tr data-name="seven_li">
			<td>7</td>
			<td>Complete your board of review.</td>
			<td> <% if(!@star.seven_li.blank?) %>
				 <%=  image_tag("checkmark.png") %>
				 <% end %>
			</td>
			<td>
        <%= f.text_field(:seven_li_date, :class => 'datepicker')%>
      </td>
		</tr>
	</tbody>
</table>
<%= javascript_tag do %>
  window.advancementId = "<%=j @star.id.to_s %>";
<% end %>
<% end %>

app/views/advancements/_test.html.erb
<h1>Test Html Erb</h1>
<h2>Hello</h2>
<%= form_for :boy_scout do |f| %>
	<%= f.label :one_li %>
	<%= f.text_field :one_li %>
	<%= f.label :one_li_date %>
	<%= f.text_field :one_li_date %>
	<%= f.label :two_li %>
	<%= f.text_field :two_li %>
	<%= f.label :two_li_date %>
	<%= f.text_field :two_li_date %>
<% end %>

app/views/advancements/edit.html.erb
<h1>Editing advancement</h1>

<%= render 'form' %>

<%= link_to 'Show', @advancement %> |
<%= link_to 'Back', advancements_path %>

app/views/advancements/new.html.erb
<h1>New advancement</h1>

<%= render 'form' %>

<%= link_to 'Back', advancements_path %>

app/views/advancements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Scout:</b>
  <%= @advancement.scout_id %>
</p>

<p>
  <b>Rank:</b>
  <%= @advancement.rank %>
</p>


<%= link_to 'Edit', edit_advancement_path(@advancement) %> |
<%= link_to 'Back', advancements_path %>

app/views/advancements/show.json.erb
"<%= @link %> "